name: mdjbe
type: laravel

webserver_type: apache-fpm
php_version: '8.2'
database:
  type: mysql
  version: '8.0'
nodejs_version: '20'

docroot: public
composer_root: .
host_db_port: '33307'

timezone: Europe/Brussels
xdebug_enabled: false
use_dns_when_possible: true
composer_version: '2'

web_extra_daemons:
  - name: react
    command: 'yarn dev --host 0.0.0.0 --port 3000'
    directory: /var/www/html/client

web_extra_exposed_ports:
  - name: react
    container_port: 3000
    http_port: 3080
    https_port: 3433

hooks:
  post-start:
    - exec: 'composer install'
    - exec: 'npm run build'

disable_settings_management: true
